apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/20481A04K2/gke-argocd-airflow.git' # <--- Change this
    targetRevision: main            # or use 'main'
    path: staging/airflow           # Path to the folder containing Chart.yaml
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true        # Automatically creates 'airflow' namespace
      - SkipDryRunOnMissingResource=true # Useful for ExternalSecrets
