apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-db-secrets
  namespace: airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: airflow-db-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Note: 'host' must be 127.0.0.1 in Secret Manager because we use the Cloud SQL Proxy sidecar
        connection: 'postgresql://{{ "{{" }} .user {{ "}}" }}:{{ "{{" }} .password {{ "}}" }}@{{ "{{" }} .host {{ "}}" }}:{{ "{{" }} .port {{ "}}" }}/postgres?sslmode=disable'
  data:
    - secretKey: host
      remoteRef:
        key: airflow-db-host # The name of the secret in GCP Secret Manager
    - secretKey: port
      remoteRef:
        key: airflow-db-port
    - secretKey: password
      remoteRef:
        key: airflow-db-password
    - secretKey: user
      remoteRef:
        key: airflow-db-user
